name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set environment variables
      - name: Set environment variables
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> $GITHUB_ENV

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Step 5: Debug env variables (optional, useful for troubleshooting)
      - name: Debug env variables
        run: |
          echo "SUPABASE_URL=$SUPABASE_URL"
          echo "SUPABASE_KEY=$SUPABASE_KEY"

      # Step 6: Run your Streamlit app or Python script
      - name: Run application
        run: |
          source venv/bin/activate
          streamlit run script.py  # Replace with your actual script filename
